extends: relaxed

rules:
    comments: enable
    comments-indentation: disable

    line-length:
        max: 170
        level: warning

    indentation:
        level: warning
        indent-sequences: consistent
